# BASE DIR -> compose
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copy all CSPROJ FIRST (better for cache)
COPY src/EventPilot.API/EventPilot.API.csproj EventPilot.API/
COPY src/EventPilot.Application/EventPilot.Application.csproj EventPilot.Application/
COPY src/EventPilot.Infrastructure/EventPilot.Infrastructure.csproj EventPilot.Infrastructure/
COPY src/EventPilot.Domain/EventPilot.Domain.csproj EventPilot.Domain/

RUN dotnet restore "EventPilot.API/EventPilot.API.csproj"

# Copy remaning files
COPY src/ .

WORKDIR "/src/EventPilot.API"
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
RUN dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EventPilot.API.dll"]