// <auto-generated />
using System;
using EventPilot.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventPilot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108145437_Add_Constraints_For_Enums")]
    partial class Add_Constraints_For_Enums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("EventPilot.Domain.Entities.Certificate", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GenerationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "EventRegistrationId");

                    b.HasIndex("EventRegistrationId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.CheckIn", b =>
                {
                    b.Property<long>("RegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckInOrigin")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistrationId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("CheckIns", t =>
                        {
                            t.HasCheckConstraint("CK_CheIn_CheckInOrigin", "[CheckInOrigin] IN (1,2)");
                        });
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Event_Status", "[Status] IN (1,2,3,4)");
                        });
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.EventRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.OrganizerEvent", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizerEvents");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.SessionRegistration", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "EventRegistrationId");

                    b.HasIndex("EventRegistrationId");

                    b.ToTable("RegistrationSessions", t =>
                        {
                            t.HasCheckConstraint("CK_SessionRegistration_Status", "[Status] IN (1,2)");
                        });
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "[Role] IN (1,2,3)");
                        });
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("EventPilot.Domain.Entities.EventRegistration", "EventRegistration")
                        .WithMany("Certificates")
                        .HasForeignKey("EventRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPilot.Domain.Entities.Session", "Session")
                        .WithMany("Certificates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventRegistration");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("EventPilot.Domain.Entities.EventRegistration", "EventRegistration")
                        .WithMany("CheckIns")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPilot.Domain.Entities.Session", "Session")
                        .WithMany("CheckIns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventRegistration");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.EventRegistration", b =>
                {
                    b.HasOne("EventPilot.Domain.Entities.Event", "Event")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPilot.Domain.Entities.User", "User")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.OrganizerEvent", b =>
                {
                    b.HasOne("EventPilot.Domain.Entities.Event", "Event")
                        .WithMany("OrganizerEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPilot.Domain.Entities.User", "User")
                        .WithMany("OrganizerEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.Session", b =>
                {
                    b.HasOne("EventPilot.Domain.Entities.Event", "Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.SessionRegistration", b =>
                {
                    b.HasOne("EventPilot.Domain.Entities.EventRegistration", "EventRegistration")
                        .WithMany("SessionRegistrations")
                        .HasForeignKey("EventRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPilot.Domain.Entities.Session", "Session")
                        .WithMany("SessionRegistrations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventRegistration");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventRegistrations");

                    b.Navigation("OrganizerEvents");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.EventRegistration", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CheckIns");

                    b.Navigation("SessionRegistrations");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.Session", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CheckIns");

                    b.Navigation("SessionRegistrations");
                });

            modelBuilder.Entity("EventPilot.Domain.Entities.User", b =>
                {
                    b.Navigation("EventRegistrations");

                    b.Navigation("OrganizerEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
